name=MoleGraphManual
version=4.4
author=e-Mole
maintainer=e-Mole <casopis.e.mole@gmail.com>
sentence=Callback-based library for custom programming of the MoleGraph school probeware system and using its multiplatform app.
paragraph=MoleGraphManual allows you to develop custom probeware firmware for Arduino NANO/UNO (ATmega 328P) with simultaneous data transmission, control external actuators, and display measurement data with MoleGraph applications (app project: https://www.molegraph.eu). It perfectly integrates with Blockly@rduino for visual programming and is optimized for advanced experimental designs.
category=Sensors
url=https://github.com/e-Mole/MoleGraphManual
architectures=avr